spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books_db
    username: postgres
    password: "%Nw8Fm1qc*HXFh3mK}|9GOzATC}8LQrh"
application:
  security:
    this-service-secret-api-key: "4Ai+5X3ZuK4J+T44sp0RDL48WeieeIq0boPRJb89MMU="